- name: Install AWX depedency
  apt: 
    name: '{{ item }}'
    state: present
  loop:
    - ansible
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent
    - unzip

- name: Add Apt signing key for Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker depedency
  apt: 
    name: '{{ item }}'
    state: present
  loop:
    - docker-ce
    - nodejs
    - npm
    - python3-pip
    - git
    - pwgen
    - vim

- name: Add user to Docker group
  user:
    name: '{{ ansible_user }}'
    group: docker
    append: yes

- name: Install requests and Docker Compose using pip
  ansible.builtin.pip:
    name: '{{ item }}'
  loop:
    - requests==2.22.0
    - docker-compose==1.25.0

- name: Download AWX package
  ansible.builtin.get_url:
    url: https://github.com/ansible/awx/archive/17.1.0.zip
    dest: '/home/{{ ansible_user }}/17.1.0.zip'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Extract awx.zp 
  ansible.builtin.unarchive:
    src: '/home/{{ ansible_user }}/17.1.0.zip'
    dest: '/home/{{ ansible_user }}'
    remote_src: yes
    keep_newer: yes

- name: Change password awx
  lineinfile: 
    path: '/home/{{ ansible_user }}/awx-17.1.0/installer/inventory'
    regexp: '^# admin_password=password'
    line: 'admin_password=Admin#1234'
    backup: yes